name: ci

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  comparison-tests:
    name: Comparison tests
    uses: ./.github/workflows/comparison-tests.yml

  execution-tests:
    name: Execution tests
    uses: ./.github/workflows/execution-tests.yml

  lint:
    uses: ./.github/workflows/lint.yml
