name: Execution Tests

on:
  workflow_call:

jobs:
  execution_test_ubuntu:
    name: Execution Tests Ubuntu
    strategy:
      matrix:
        node: [26, 24, 22]
        ts: [5.7.2, 5.8.2, 5.9.2, 6.0.2] # next excluded for now
        webpack: [4, 5]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: install node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node }}

      - uses: ./.github/actions/build-ts-loader

      - name: install typescript
        run: yarn add typescript@${{ matrix.ts }}

      - name: install webpack 4
        if: matrix.webpack == 4
        run: yarn add webpack@^4.47.0 karma-webpack@^4.0.2

      - name: test
        run: yarn execution-tests

  # execution_test_macos:
  #   name: Execution Tests macOS
  #   strategy:
  #     matrix:
  #       node: [26, 24, 22]
  #       ts: [5.7.2, 5.8.2, 5.9.2, 6.0.2] # next excluded for now
  #       webpack: [4, 5]
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v7

  #     - name: install node
  #       uses: actions/setup-node@v7
  #       with:
  #         node-version: ${{ matrix.node }}

  #     - uses: ./.github/actions/build-ts-loader

  #     - name: install typescript
  #       run: yarn add typescript@${{ matrix.ts }}

  #     - name: install webpack 4
  #       if: matrix.webpack == 4
  #       run: yarn add webpack@^4.47.0 karma-webpack@^4.0.2

  #     - name: test
  #       run: yarn execution-tests

  execution_test_windows:
    name: Execution Tests Windows
    strategy:
      matrix:
        node: [26, 24, 22]
        ts: [5.7.2, 5.8.2, 5.9.2, 6.0.2] # next excluded for now
        webpack: [4, 5]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7

      - name: install node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node }}

      - uses: ./.github/actions/build-ts-loader
        with:
          working-directory: C:\source\ts-loader

      - name: install typescript
        run: yarn add typescript@${{ matrix.ts }}
        working-directory: C:\source\ts-loader

      - name: install webpack 4
        if: matrix.webpack == 4
        run: yarn add webpack@^4.47.0 karma-webpack@^4.0.2
        working-directory: C:\source\ts-loader

      - name: test
        run: yarn execution-tests
        working-directory: C:\source\ts-loader
