on:
  release:
    types: [published]

name: release

# Permission to generate an OIDC token for trusted publishing to npm
permissions:
  id-token: write
  contents: read

jobs:
  build_test_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: install node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/

      - name: install
        run: yarn install

      - name: build
        run: yarn build

      # - name: test
      #   run: yarn execution-tests

      - run: npm install -g npm@latest

      - run: npm publish
        env:
          NPM_CONFIG_PROVENANCE: true
          # NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}} no longer needed with trusted publishing and OIDC token generation